language: python
python:
  - "2.7"
before_script:
  - npm install
script:
  - grunt test
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && grunt deploy
notifications:
  email: false